"""Add Bonita tracking fields to observaciones table

Revision ID: 27f3ae1641bf
Revises: ce40702b58f1
Create Date: 2025-11-25 17:24:24.356539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27f3ae1641bf'
down_revision = 'ce40702b58f1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('observaciones', sa.Column('bonita_case_id', sa.String(length=100), nullable=True))
    op.add_column('observaciones', sa.Column('bonita_process_instance_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('observaciones', 'bonita_process_instance_id')
    op.drop_column('observaciones', 'bonita_case_id')
    # ### end Alembic commands ###
