"""Add observaciones table

Revision ID: 5f3895cf05d2
Revises: e88571dbba0e
Create Date: 2025-11-11 17:28:54.506271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f3895cf05d2'
down_revision = 'e88571dbba0e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('observaciones',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('proyecto_id', sa.UUID(), nullable=False),
    sa.Column('council_user_id', sa.UUID(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('estado', sa.Enum('PENDIENTE', 'RESUELTA', 'VENCIDA', name='estadoobservacion'), nullable=False),
    sa.Column('fecha_limite', sa.Date(), nullable=False),
    sa.Column('respuesta', sa.Text(), nullable=True),
    sa.Column('fecha_resolucion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['council_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['proyecto_id'], ['proyectos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_table('observaciones')
    # ### end Alembic commands ###
