"""Add observaciones table

Revision ID: 7a84d4a6d23b
Revises: 5f3895cf05d2
Create Date: 2025-11-11 17:34:07.458525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a84d4a6d23b'
down_revision = '5f3895cf05d2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
