"""Add timestamps to pedidos table

Revision ID: a1b2c3d4e5f6
Revises: 27f3ae1641bf
Create Date: 2025-11-26 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1b2c3d4e5f6'
down_revision = '27f3ae1641bf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pedidos', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False))
    op.add_column('pedidos', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False))
    op.add_column('pedidos', sa.Column('fecha_comprometido', sa.DateTime(timezone=True), nullable=True))
    op.add_column('pedidos', sa.Column('fecha_completado', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pedidos', 'fecha_completado')
    op.drop_column('pedidos', 'fecha_comprometido')
    op.drop_column('pedidos', 'updated_at')
    op.drop_column('pedidos', 'created_at')
    # ### end Alembic commands ###
