"""Add timestamps to etapas table

Revision ID: b2c3d4e5f6a7
Revises: a1b2c3d4e5f6
Create Date: 2025-11-26 12:01:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2c3d4e5f6a7'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('etapas', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False))
    op.add_column('etapas', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False))
    op.add_column('etapas', sa.Column('fecha_en_ejecucion', sa.DateTime(timezone=True), nullable=True))
    op.add_column('etapas', sa.Column('fecha_financiada', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('etapas', 'fecha_financiada')
    op.drop_column('etapas', 'fecha_en_ejecucion')
    op.drop_column('etapas', 'updated_at')
    op.drop_column('etapas', 'created_at')
    # ### end Alembic commands ###
