"""Simplify proyecto estados and add estado to etapas

Revision ID: c222f92ef84b
Revises: 26e1c5debbec
Create Date: 2025-11-11 18:25:54.469986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c222f92ef84b'
down_revision = '26e1c5debbec'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # 1. Migrate proyecto estados from old to new BEFORE modifying enum
    # Use temporary varchar column to avoid enum validation during migration
    op.execute("ALTER TABLE proyectos ALTER COLUMN estado TYPE varchar(50)")
    op.execute("UPDATE proyectos SET estado = 'en_planificacion' WHERE estado IN ('borrador', 'buscando_financiamiento')")

    # 2. Recreate EstadoProyecto enum with only 3 values
    op.execute("DROP TYPE IF EXISTS estadoproyecto CASCADE")
    op.execute("CREATE TYPE estadoproyecto AS ENUM ('en_planificacion', 'en_ejecucion', 'completo')")
    op.execute("ALTER TABLE proyectos ALTER COLUMN estado TYPE estadoproyecto USING estado::estadoproyecto")

    # 3. Add fecha_completitud to proyectos
    op.add_column('proyectos', sa.Column('fecha_completitud', sa.DateTime(timezone=True), nullable=True))

    # 4. Create EstadoEtapa enum type in PostgreSQL
    estado_etapa_enum = sa.Enum('EN_PROGRESO', 'COMPLETADA', name='estadoetapa')
    estado_etapa_enum.create(op.get_bind(), checkfirst=True)

    # 5. Add new columns for etapas
    op.add_column('etapas', sa.Column('estado', estado_etapa_enum, nullable=False, server_default='EN_PROGRESO'))
    op.add_column('etapas', sa.Column('fecha_completitud', sa.DateTime(timezone=True), nullable=True))

    # Keep the indexes - they are useful for performance
    # (Alembic detected them as removed but we want to keep them)
    # The indexes already exist from previous migration, so we don't need to recreate them
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove new columns
    op.drop_column('proyectos', 'fecha_completitud')
    op.drop_column('etapas', 'fecha_completitud')
    op.drop_column('etapas', 'estado')

    # Note: Cannot restore borrador/buscando_financiamiento estados
    # All projects will remain in en_planificacion/en_ejecucion/completo
    # ### end Alembic commands ###
