"""Add execution timestamps to proyectos table

Revision ID: c3d4e5f6a7b8
Revises: b2c3d4e5f6a7
Create Date: 2025-11-26 12:02:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3d4e5f6a7b8'
down_revision = 'b2c3d4e5f6a7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proyectos', sa.Column('fecha_en_ejecucion', sa.DateTime(timezone=True), nullable=True))
    op.add_column('proyectos', sa.Column('fecha_finalizado', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('proyectos', 'fecha_finalizado')
    op.drop_column('proyectos', 'fecha_en_ejecucion')
    # ### end Alembic commands ###
