"""Add ofertas table and user_id to proyectos

Revision ID: c4cd300b3a8d
Revises: 480654690751
Create Date: 2025-10-20 19:57:34.720018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4cd300b3a8d'
down_revision = '480654690751'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create ofertas table
    op.create_table('ofertas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pedido_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('monto_ofrecido', sa.Float(), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('estado', sa.Enum('PENDIENTE', 'ACEPTADA', 'RECHAZADA', name='estadooferta'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )

    # Add user_id column to proyectos (nullable temporarily to allow migration)
    op.add_column('proyectos', sa.Column('user_id', sa.UUID(), nullable=True))

    # TODO: If you have existing proyectos, you need to update them with a user_id before making it NOT NULL
    # Example: op.execute("UPDATE proyectos SET user_id = (SELECT id FROM users LIMIT 1)")

    # Make user_id NOT NULL
    op.alter_column('proyectos', 'user_id', nullable=False)

    # Create foreign key constraint
    op.create_foreign_key('fk_proyectos_user_id', 'proyectos', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop ofertas table
    op.drop_table('ofertas')

    # Drop foreign key and column from proyectos
    op.drop_constraint('fk_proyectos_user_id', 'proyectos', type_='foreignkey')
    op.drop_column('proyectos', 'user_id')

    # Drop enum type
    sa.Enum(name='estadooferta').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
