"""Add esperando_ejecucion state to etapas

Revision ID: ce40702b58f1
Revises: e3a4711db50c
Create Date: 2025-11-21 19:32:54.485523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce40702b58f1'
down_revision = 'e3a4711db50c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
