"""Add Bonita tracking fields to etapas

Revision ID: e3a4711db50c
Revises: 0ec59ed902de
Create Date: 2025-11-21 17:45:19.087713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3a4711db50c'
down_revision = '0ec59ed902de'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('etapas', sa.Column('bonita_case_id', sa.String(length=100), nullable=True))
    op.add_column('etapas', sa.Column('bonita_process_instance_id', sa.Integer(), nullable=True))
    op.drop_index(op.f('idx_proyectos_ciudad'), table_name='proyectos')
    op.drop_index(op.f('idx_proyectos_created_at'), table_name='proyectos')
    op.drop_index(op.f('idx_proyectos_estado'), table_name='proyectos')
    op.drop_index(op.f('idx_proyectos_pais'), table_name='proyectos')
    op.drop_index(op.f('idx_proyectos_provincia'), table_name='proyectos')
    op.drop_index(op.f('idx_proyectos_tipo'), table_name='proyectos')
    op.drop_index(op.f('idx_proyectos_updated_at'), table_name='proyectos')
    op.drop_index(op.f('idx_proyectos_user_id'), table_name='proyectos')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_proyectos_user_id'), 'proyectos', ['user_id'], unique=False)
    op.create_index(op.f('idx_proyectos_updated_at'), 'proyectos', ['updated_at'], unique=False)
    op.create_index(op.f('idx_proyectos_tipo'), 'proyectos', ['tipo'], unique=False)
    op.create_index(op.f('idx_proyectos_provincia'), 'proyectos', ['provincia'], unique=False)
    op.create_index(op.f('idx_proyectos_pais'), 'proyectos', ['pais'], unique=False)
    op.create_index(op.f('idx_proyectos_estado'), 'proyectos', ['estado'], unique=False)
    op.create_index(op.f('idx_proyectos_created_at'), 'proyectos', ['created_at'], unique=False)
    op.create_index(op.f('idx_proyectos_ciudad'), 'proyectos', ['ciudad'], unique=False)
    op.drop_column('etapas', 'bonita_process_instance_id')
    op.drop_column('etapas', 'bonita_case_id')
    # ### end Alembic commands ###
