"""Initial schema with proyectos, etapas, pedidos

Revision ID: f39824fbbcd0
Revises: 
Create Date: 2025-10-20 14:39:13.853005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f39824fbbcd0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proyectos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('tipo', sa.String(length=100), nullable=False),
    sa.Column('pais', sa.String(length=100), nullable=False),
    sa.Column('provincia', sa.String(length=100), nullable=False),
    sa.Column('ciudad', sa.String(length=100), nullable=False),
    sa.Column('barrio', sa.String(length=100), nullable=True),
    sa.Column('estado', sa.Enum('BORRADOR', 'EN_PLANIFICACION', 'BUSCANDO_FINANCIAMIENTO', 'EN_EJECUCION', 'COMPLETO', name='estadoproyecto'), nullable=False),
    sa.Column('bonita_case_id', sa.String(length=100), nullable=True),
    sa.Column('bonita_process_instance_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('etapas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('proyecto_id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['proyecto_id'], ['proyectos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pedidos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('etapa_id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.Enum('ECONOMICO', 'MATERIALES', 'MANO_OBRA', 'TRANSPORTE', 'EQUIPAMIENTO', name='tipopedido'), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('monto', sa.Float(), nullable=True),
    sa.Column('moneda', sa.String(length=10), nullable=True),
    sa.Column('cantidad', sa.Integer(), nullable=True),
    sa.Column('unidad', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['etapa_id'], ['etapas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pedidos')
    op.drop_table('etapas')
    op.drop_table('proyectos')
    # ### end Alembic commands ###
